### ISSUE TITLE
Render Markdown tables

### ISSUE THREAD

**Issue by MasterEvarior** [BrettThurs10/DNDFetch#4]
Should the Markdown tables in the content of the card be rendered?

Currently it looks like this:
![image](https://user-images.githubusercontent.com/36074738/107374443-e2344c80-6ae7-11eb-9558-c08b9d9f7344.png)

**Comment by BrettThurs10** [comment]
Great catch! I'll fix that. Totally overlooked it.

**Comment by BrettThurs10** [comment]
Sorry for the late reply. Thanks for picking this up!
